services:
  - type: web
    name: chilka-backend
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push --skip-generate && npx prisma db seed && node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: chilka-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000
      - key: CORS_ORIGINS
        value: "*"
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false

databases:
  - name: chilka-db
    plan: free
    databaseName: db_flutter
    user: chilka
